/** Rotas indexáveis — espelho de src/constants/routes.ts para scripts de build */
export const SITE_URL = 'https://calculojuroscompostos.com.br';

export const INDEXABLE_PATHS = [
  '/',
  '/juros-compostos',
  '/calculadora-cdi',
  '/calculadora-ipca',
  '/clt-pj',
  '/aposentadoria',
  '/rescisao-trabalhista',
  '/conversor-de-moedas',
  '/calculadora/juros-compostos',
  '/calculadora/clt-vs-pj',
  '/calculadora/aposentadoria',
  '/calculadora/rescisao-trabalhista',
  '/blog',
  '/blog/como-calcular-juros-compostos',
  '/blog/quanto-investir-para-se-aposentar',
  '/blog/cdi-ou-poupanca',
  '/blog/tesouro-direto-vale-a-pena',
  '/blog/como-sair-das-dividas',
  '/sobre',
  '/politica-de-privacidade',
  '/termos-de-uso',
  '/politica-de-cookies',
  '/isencao-de-responsabilidade',
  '/categoria/investimentos',
  '/categoria/financas-pessoais',
  '/categoria/aposentadoria',
  '/categoria/emprestimos',
  '/categoria/salario-clt',
  '/categoria/impostos',
  '/categoria/empreendedorismo',
];
